# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48b48eedcbafdae96a9965bdff802035cb9fdd0d60cdd7025616a6a0f8b9105839c1f7384a8c927f0db3ac03f174abcf98c9db18b4e4f74a56635ca43805a928

test:
  secret_key_base: 2749d34b145bba7a57a59c7aecd25205d9bb00e973cf274f3b3b5136c5efafec8307e151c085689f11fc5472228e3334fa64c226a64cf67412fe313c53d18f92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
